---
language: en-GB,en
version: "0.2"
caseSensitive: true
noConfigSearch: true
words:
  - BFDADC
  - CODECOV
  - CODEOWNERS
  - CONVENTIONALCOMMITS
  - Codecov
  - DEVSKIM
  - Datasources
  - FBCA
  - GITHUB
  - IntelliJ
  - Kanellis
  - Kanellos
  - akikanellis
  - amannn
  - ansible
  - automerge
  - bcoe
  - codecov
  - conventionalcommits
  - cycjimmy
  - datasource
  - direnv
  - envrc
  - github
  - hmarr
  - justfile
  - kics
  - kotlin
  - lcov
  - markdownlint
  - megalinter
  - noreply
  - releaserc
  - renovatebot
  - sdatasource
  - temurin
  - wontfix
