---
APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
FLAVOR_SUGGESTIONS: false
FORMATTERS_DISABLE_ERRORS: false
SHOW_ELAPSED_TIME: true

VALIDATE_ALL_CODEBASE: false

IGNORE_GENERATED_FILES: true
ADDITIONAL_EXCLUDED_DIRECTORIES: [dist]
FILTER_REGEX_EXCLUDE: "CHANGELOG.md"

DISABLE_LINTERS:
  # We are using Prettier instead
  - JAVASCRIPT_STANDARD
  # See: https://github.com/oxsecurity/megalinter/issues/2849
  - REPOSITORY_DEVSKIM
  # We are using Prettier instead
  - TYPESCRIPT_STANDARD
  # TODO re-enable
  - EDITORCONFIG_EDITORCONFIG_CHECKER

JAVASCRIPT_DEFAULT_STYLE: prettier

# MegaLinter has a bug that does not respect `threshold` option in JSCPD
# See: https://github.com/oxsecurity/megalinter/issues/2450
COPYPASTE_JSCPD_COMMAND_REMOVE_ARGUMENTS:
  - --exitCode
  - "1"

TYPESCRIPT_DEFAULT_STYLE: prettier
