---
APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
FLAVOR_SUGGESTIONS: false
SHOW_ELAPSED_TIME: true

VALIDATE_ALL_CODEBASE: false

IGNORE_GENERATED_FILES: true
FILTER_REGEX_EXCLUDE: "^(\
  CHANGELOG\\.md|\
  .+/bundle/.+\
  )$"

DISABLE_LINTERS:
  # We are using Prettier instead
  - JAVASCRIPT_STANDARD
  # See: https://github.com/oxsecurity/megalinter/issues/2849
  - REPOSITORY_DEVSKIM
  # We are using Prettier instead
  - TYPESCRIPT_STANDARD

JAVASCRIPT_DEFAULT_STYLE: prettier

# editorconfig-checker does not automatically detect .ecrc.json
EDITORCONFIG_EDITORCONFIG_CHECKER_CONFIG_FILE: .ecrc.json

# MegaLinter only passes in `.json` files by default
JSON_PRETTIER_FILE_EXTENSIONS: [.json, .json5]
JSON_V8R_FILE_EXTENSIONS: [.json, .json5]

TYPESCRIPT_DEFAULT_STYLE: prettier
