---
preset: conventionalcommits
branches: main

plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: refactor
          release: patch
        - type: build
          release: patch
        - type: ci
          release: patch
  - - "@semantic-release/release-notes-generator"
    - presetConfig:
        # this overrides the entire `types` property so all the types have to be
        # redefined
        types:
          # default types
          - type: feat
            section: Features
          - type: feature
            section: Features
          - type: fix
            section: Bug Fixes
          - type: perf
            section: Performance Improvements
          - type: revert
            section: Reverts

          # types that were hidden by default
          - type: docs
            section: Documentation
          - type: chore
            section: Miscellaneous Chores
          - type: refactor
            section: Code Refactoring
          - type: test
            section: Tests
          - type: build
            section: Build System
          - type: ci
            section: Continuous Integration
  - "@semantic-release/changelog"
  - - semantic-release-replace-plugin
    - replacements:
        - files: [README.md]
          from: akikanellis/branch-name-validator-test@v\d+\.\d+\.\d+
          to: akikanellis/branch-name-validator-test@v${nextRelease.version}
          results:
            - file: README.md
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
  - "@semantic-release/npm"
  - - "@semantic-release/exec"
    - prepareCmd: npm run package
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - dist
        - package.json
        - package-lock.json
        - README.md
  - "@semantic-release/github"
