---
blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/akikanellis/branch-name-validator-test/discussions
    about: Please ask and answer questions here.
