---
name: Build Main

"on":
  push:
    branches: [main]

permissions: {}

env:
  # renovate: datasource=npm depName=@semantic-release/changelog
  SEMANTIC_RELEASE_CHANGELOG_VERSION: 6.0.3

  # renovate: datasource=npm depName=@semantic-release/exec
  SEMANTIC_RELEASE_EXEC_VERSION: 6.0.3

  # renovate: datasource=npm depName=@semantic-release/git
  SEMANTIC_RELEASE_GIT_VERSION: 10.0.1

  # renovate: datasource=npm depName=@semantic-release/npm
  SEMANTIC_RELEASE_NPM_VERSION: 11.0.1

  # renovate: datasource=npm depName=conventional-changelog-conventionalcommits
  CONVENTIONAL_CHANGELOG_CONVENTIONALCOMMITS_VERSION: 6.1.0

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

    permissions:
      contents: read

    with:
      continue-on-error: true

  test:
    name: Test
    uses: ./.github/workflows/test.yml

    permissions:
      contents: read

    with:
      continue-on-error: true

  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}-release

    permissions:
      contents: read

    outputs:
      release-published: ${{ steps.release.outputs.new_release_published }}
      release-version: ${{ steps.release.outputs.new_release_version }}

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Setup just
        # yamllint disable-line rule:line-length
        uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d # v1.6.0
        with:
          # renovate: datasource=crate depName=just
          just-version: 1.16.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        # yamllint disable-line rule:line-length
        uses: actions/setup-node@v4.0.0
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install dependencies
        run: just install-dependencies

      - name: Release
        id: release
        # yamllint disable-line rule:line-length
        uses: cycjimmy/semantic-release-action@61680d0e9b02ff86f5648ade99e01be17f0260a4 # v4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: aki-bot[bot]
          GIT_AUTHOR_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: aki-bot[bot]
          GIT_COMMITTER_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
        with:
          # renovate: datasource=npm depName=semantic-release
          semantic_version: 21.1.2
          extra_plugins: "@semantic-release/changelog@\
            ${{ env.SEMANTIC_RELEASE_CHANGELOG_VERSION }} \
            @semantic-release/exec@\
            ${{ env.SEMANTIC_RELEASE_EXEC_VERSION }} \
            @semantic-release/git@\
            ${{ env.SEMANTIC_RELEASE_GIT_VERSION }} \
            @semantic-release/npm@\
            ${{ env.SEMANTIC_RELEASE_NPM_VERSION }} \
            conventional-changelog-conventionalcommits@\
            ${{ env.CONVENTIONAL_CHANGELOG_CONVENTIONALCOMMITS_VERSION }}"

  ## TODO remove this
  test-release-locally:
    name: Test release
    needs: release
    if: needs.release.outputs.release-published == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: v${{ needs.release.outputs.release-version }}

      - name: Validate branch name
        id: validate-branch-name
        # kics-scan ignore-line
        uses: ./
        with:
          regex: ^[a-z]+([a-z0-9\.-])+$

  test-release-static:
    name: Test release static
    needs: release
    if: needs.release.outputs.release-published == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Validate branch name
        # kics-scan ignore-line
        uses: akikanellis/branch-name-validator-test@v1.5.20
        with:
          regex: ^[a-z]+([a-z0-9\.-])+$
## TODO this doesn't work because GitHub doesn't support dynamic `uses:`
#  test-release-marketplace:
#    name: Test release marketplace
#    needs: release
#    if: needs.release.outputs.release-published == 'true'
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Validate branch name
# yamllint disable-line rule:line-length
#        uses: akikanellis/branch-name-validator-test@v${{ needs.release.outputs.release-version }}
#        with:
#          regex: ^[a-z]+([a-z0-9\.-])+$
