---
name: Build Main

"on":
  push:
    branches: [main]

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}-release
    permissions:
      contents: read
    outputs:
      release-published: ${{ steps.release.outputs.new_release_published }}
      release-version: ${{ steps.release.outputs.new_release_version }}
      release-git-tag: ${{ steps.release.outputs.new_release_git_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install dependencies
        run: npm ci && npm run install:dependencies

      - name: Get token
        id: get-token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.AKI_BOT_APP_ID }}
          application_private_key: ${{ secrets.AKI_BOT_APP_PRIVATE_KEY }}
          permissions: >
            contents:write,
            issues:write,
            pull_requests:write

      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@cb425203a562475bca039ba4dbf90c7f9ac790f4 # v4.1.0
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
          GIT_AUTHOR_NAME: aki-bot[bot]
          GIT_AUTHOR_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: aki-bot[bot]
          GIT_COMMITTER_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
        with:
          semantic_version: 21.1.2

  lint:
    name: Lint
    needs: release
    if: needs.release.outputs.release-published == 'true'
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: read
    with:
      git-ref: ${{ needs.release.outputs.release-git-tag }}
      continue-on-error: true
      apply-fixes: false

  test:
    name: Test
    needs: release
    if: needs.release.outputs.release-published == 'true'
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
    with:
      git-ref: ${{ needs.release.outputs.release-git-tag }}
      continue-on-error: true
      update-build-system-cache: true
    secrets:
      NX_CLOUD_ACCESS_READ_WRITE_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_READ_WRITE_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-release:
    name: Test release
    needs: release
    if: needs.release.outputs.release-published == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ needs.release.outputs.release-git-tag || github.ref }}

      - name: Validate branch name
        id: validate-branch-name
        # kics-scan ignore-line
        uses: ./
        with:
          regex: ^[a-z]+([a-z0-9\.-])+$
