---
name: Build PR

"on":
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  validate-branch-name:
    name: Validate branch name
    runs-on: ubuntu-latest

    steps:
      # TODO remove this
      - name: Validate branch name
        id: validate-branch-name
        uses: ./
        with:
          regex: ^[a-z]+([a-z0-9\.-])+$
