---
name: Lint

"on":
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        description: Allow a workflow run to pass when this workflow fails
        required: false
        default: false
      apply-fixes:
        type: boolean
        description: Apply linter fixes
        required: true
    secrets:
      AKI_BOT_APP_ID:
        description: The aki-bot app ID
        required: false
      AKI_BOT_APP_PRIVATE_KEY:
        description: The aki-bot app private key
        required: false

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}

    steps:
      - name: Get token
        id: get-token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        if: ${{ inputs.apply-fixes }}
        with:
          application_id: ${{ secrets.AKI_BOT_APP_ID }}
          application_private_key: ${{ secrets.AKI_BOT_APP_PRIVATE_KEY }}
          permissions: >
            contents:write,
            issues:write,
            pull_requests:write

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ inputs.apply-fixes && steps.get-token.outputs.token || github.token }}
          fetch-depth: 0

      - name: Setup just
        uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d # v1.6.0
        with:
          just-version: 1.23.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install dependencies
        run: just install-dependencies

      - name: Lint
        id: lint
        uses: oxsecurity/megalinter@7e042c726c68415475b05a65a686c612120a1232 # v7.7.0
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
          APPLY_FIXES: ${{ inputs.apply-fixes && 'all' || 'none' }}

      - name: Commit and push linter fixes
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
        if: ${{ inputs.apply-fixes && steps.lint.outputs.has_updated_sources == 1 }}
        with:
          commit_user_name: aki-bot[bot]
          commit_user_email: 103840025+aki-bot[bot]@users.noreply.github.com
          commit_author: aki-bot <103840025+aki-bot[bot]@users.noreply.github.com>
          commit_message: "refactor: apply linter fixes"
