---
name: Lint

"on":
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        description: Allow a workflow run to pass when this workflow fails
        required: false
        default: false
      apply-fixes:
        type: boolean
        description: Apply linter fixes
        required: false
        default: true

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}

    # TODO fix for megalinter
    permissions:
      contents: read

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Lint
        # yamllint disable-line rule:line-length
        uses: oxsecurity/megalinter@v7.7.0
        env:
          APPLY_FIXES: ${{ inputs.apply-fixes == 'true' && 'all' || 'none' }}

      - name: Get token
        id: get-token
        # yamllint disable-line rule:line-length
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # tag=v2.1.0
        if: ${{ inputs.apply-fixes }}
        with:
          application_id: ${{ secrets.AKI_BOT_APP_ID }}
          application_private_key: ${{ secrets.AKI_BOT_APP_PRIVATE_KEY }}
          # TODO permissions might need to be relaxed (do we need issues and pull_requests)
          permissions: >
            contents:write,
            issues:write,
            pull_requests:write

      - name: Commit and push linter fixes
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        if: ${{ inputs.apply-fixes }}
        with:
          token: ${{ steps.get-token.outputs.token }}

          commit_user_name: aki-bot[bot]
          commit_user_email: 103840025+aki-bot[bot]@users.noreply.github.com
          commit_author: aki-bot <103840025+aki-bot[bot]@users.noreply.github.com>
          commit_message: "build: apply linter fixes"
