---
name: Test

"on":
  workflow_call:
    inputs:
      git-ref:
        type: string
        description: The git ref to checkout
        required: false
      continue-on-error:
        type: boolean
        description: Allow a workflow run to pass when this workflow fails
        required: false
        default: false
      update-build-system-cache:
        type: boolean
        description: Update build system cache
        required: false
        default: false
    secrets:
      NX_CLOUD_ACCESS_READ_WRITE_TOKEN:
        description: A read-write Nx Cloud access token
        required: false

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}
    permissions:
      contents: read
    steps:
      - name: Set Nx Cloud access token
        if: ${{ inputs.update-build-system-cache }}
        run: echo "NX_CLOUD_ACCESS_TOKEN=${{ secrets.NX_CLOUD_ACCESS_READ_WRITE_TOKEN }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ inputs.git-ref || github.ref }}

      - name: Setup Node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install dependencies
        run: npm ci && npm run install:dependencies

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
