---
name: Test

"on":
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        description: Allow a workflow run to pass when this workflow fails
        required: false
        default: false

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup just
        uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d # v1.6.0
        with:
          just-version: 1.16.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install dependencies
        run: just install-dependencies

      - name: Test
        run: just test

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
