---
name: Update Dependencies

"on":
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get token
        id: get-token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.AKI_BOT_APP_ID }}
          application_private_key: ${{ secrets.AKI_BOT_APP_PRIVATE_KEY }}
          permissions: >
            contents:write,
            issues:write,
            pull_requests:write,
            workflows:write

      - name: Update dependencies
        uses: renovatebot/github-action@b8ce565a2e98de1fec9696a76fba7beb01ec29b2 # v39.2.3
        with:
          renovate-version: 37.110
          configurationFile: renovate.json5
          # kics-scan ignore-line
          token: x-access-token:${{ steps.get-token.outputs.token }}
        env:
          LOG_LEVEL: debug
